disabled_rules:
  - switch_case_alignment

type_name:
  allowed_symbols: ["_"]
  min_length: 2
  max_length: 
    warning: 80
    error: 150
  unallowed_symbols_severity: warning
  validates_start_with_lowercase: error

identifier_name: 
  min_length:
    warning: 0
    error: 0
  max_length:
    warning: 60
  allowed_symbols: ["_"]

type_body_length:
    warning: 1000
    error: 1500

vertical_whitespace:
  max_empty_lines: 3

line_length:
  warning: 200
  error: 360

file_length:
  warning: 1500
  error: 3000

nesting:
  type_level:
    warning: 2

function_parameter_count:
    warning: 10
    error: 50

included: 
  - UITests
  # - Frameworks/Core/Main

excluded:
  - build
  - .build
  - Carthage

